//
//  CATypes.swift
//  TimeExplorer
//
//  Created by Krishna Venkatramani on 14/09/2022.
//

import Foundation

enum Department: String, CaseIterable {
	case african = "African Art"
	case american = "American Painting and Sculpture"
	case americas = "Art of the Americas"
	case chinese = "Chinese Art"
	case contemporary = "Contemporary Art"
	case decorative = "Decorative Art and Design"
	case drawing = "Drawings"
	case egyptian = "Egyptian and Ancient Near Eastern Art"
	case european = "European Painting and Sculpture"
	case greek_and_roman = "Greek and Roman Art"
	case indian_and_south_asia = "Indian and South East Asian Art"
	case islamic = "Islamic Art"
	case japanese = "Japanese Art"
	case korean = "Korean Art"
	case medieval = "Medieval Art"
	case modern_european = "Modern European Painting and Sculpture"
	case oceania = "Oceania"
	case art_music_film = "Performing Arts, Music, & Film"
	case photography = "Photography"
	case prints = "Prints"
	case textile = "Textiles"
}

enum Types: String, CaseIterable {
	case amulets = "Amulets"
	case apparatus = "Apparatus"
	case armsAndArmor = "Arms and Armor"
	case basketry = "Basketry"
	case bookBinding = "Book Binding"
	case boundVolume = "Bound Volume"
	case calligraphy = "Calligraphy"
	case carpet = "Carpet"
	case ceramic = "Ceramic"
	case coins = "Coins"
	case cosmeticObjects = "Cosmetic Objects"
	case drawing = "Drawing"
	case embroidery = "Embroidery"
	case enamel = "Enamel"
	case forgery = "Forgery"
	case frame = "Frame"
	case funerary = "Funerary"
	case equipment = "Equipment"
	case furnitureAndwoodwork = "Furniture and woodwo"
	case garment = "Garment"
	case glass = "Glass"
	case glyptic = "Glyptic"
	case illumination = "Illumination"
	case implements = "Implements"
	case inlays = "Inlays"
	case ivory = "Ivory"
	case jade = "Jade"
	case jewelry = "Jewelry"
	case knitting = "Knitting"
	case lace = "Lace"
	case lacquer = "Lacquer"
	case leather = "Leather"
	case linoleumBlock = "Linoleum Block"
	case lithographicStone = "Lithographic Stone"
	case manuscript = "Manuscript"
	case metalwork = "Metalwork"
	case miniature = "Miniature"
	case miscellaneous = "Miscellaneous"
	case mixedMedia = "Mixed Media"
	case monotype = "Monotype"
	case mosaic = "Mosaic"
	case musicalInstrument = "Musical Instrument"
	case netsuke = "Netsuke"
	case painting = "Painting"
	case papyri = "Papyri"
	case photograph = "Photograph"
	case plaque = "Plaque"
	case plate = "Plate"
	case portfolio = "Portfolio"
	case portraitMiniature = "Portrait Miniature"
	case `print` = "Print"
	case relief = "Relief"
	case rockCrystal = "Rock crystal"
	case rubbing = "Rubbing"
	case sampler = "Sampler"
	case scarabs = "Scarabs"
	case sculpture =  "Sculpture"
	case seals = "Seals"
	case silver = "Silver"
	case spindleWhorl = "Spindle Whorl"
	case stencil = "Stencil"
	case stone = "Stone"
	case tapestry = "Tapestry"
	case textile = "Textile"
	case timeBasedMedia = "Time-based Media"
	case tool = "Tool"
	case velvet = "Velvet"
	case vessels = "Vessels"
	case wood = "Wood"
	case woodblock = "Woodblock"
}
